### ISSUE TITLE
Add `_gl=` paramter to globalRules ( used by Google Analytics )

### ISSUE THREAD

**Issue by yuji-hatakeyama** [ClearURLs/Rules#19]
Hi !  I want to add in `data.json`  to `$.globalRules. rules[]` `_gl=` parameter .

It has been used by Google Analytics for cross site measurement.
official document: https://developers.google.com/gtagjs

**Comment by KevinRoebert** [comment]
Closed by https://github.com/ClearURLs/Rules/commit/c2a354bad57019aebe3f8bc16d8386fc9632cb9b

**Comment by yuji-hatakeyama** [comment]
Thank you for your support !
