### ISSUE TITLE
Facbook __ctf__[0] param

### ISSUE THREAD

**Issue by burtek** [ClearURLs/Rules#24]
Extension does not remove `__cft__[0]` param from FB url, i.e. https://www.facebook.com/ChmielnaDeptakiem/posts/943278472970978?__cft__[0]=AZVDjkAKDaOBrK5Q3KjYWycYjiv5AHZxLqELoBVYtgPQf9Hy-iV3kF3Cb3qUFMTw0kEoCb5Fc56L4BtVenaAsySk1phrdXvYHnRJH82olb286fJxj_3fizOFCzsd8jthKMZbXxUd3hy7m1b2PrVktuLJ&__tn__=%2CO%2CP-R

**Comment by KevinRoebert** [comment]
Closed by https://github.com/ClearURLs/Rules/commit/b90cd66d3152e24f2b1ffe8df80b3a117a443efa
