### ISSUE TITLE
twitter tracking parameter not removed

### ISSUE THREAD

**Issue by rrerrptile** [ClearURLs/Rules#31]
Example: `https://twitter.com/pichuboo/status/1451372407655071747?t=ZE3U5N82pY-lifLdzX0dvQ&s=19`
Any s= gets removed properly, but the t= tracking parameter never gets removed, even if s= is not used. About a month ago, it was actually removing both for a week or so, now it only does one.

**Comment by rrerrptile** [comment]
Okay I just learned this was actually fixed a little bit ago and reverted since it was causing issues. In the meanwhile, is there any way for me to use my own custom rules that dont require me to host the rules file online?

**Comment by iam-py-test** [comment]
Not sure if this is a prefect solution, but you could host a local server on your device (i.e. with `sudo python3 -m http.server`) and then subscribe to the rules from `http://localhost:8000/rules.txt`

**Comment by rrerrptile** [comment]
no dice. I can access the file in the browser when I host it like that, but the addon seems to ignore my custom ruleset

**Comment by rrerrptile** [comment]
Still no dice. I even made the hash file the same way as the gitlab generates it: `sha256sum data.minify.json | awk '{print $1}' > rules.minify.hash` I've verified it even outputs the same hash on an existing rules file as the gitlab artifacts.

**Comment by KevinRoebert** [comment]
Can you export your ClearURLs settings and attach them to the issue or email me to support (at) clearurls.xyz

**Comment by rrerrptile** [comment]
[CUserver.zip](https://github.com/ClearURLs/Rules/files/8149140/CUserver.zip)

**Comment by amalic** [comment]
@KevinRoebert I've created a pull request. I didn't test it because it's quite annoying that it requires a sha256 hash file to work which seemed to be too much work for such a small change.

**Comment by KevinRoebert** [comment]
@amalic The rule for the `t` parameter was intentionally removed. This field is also used for URLs in emails sent by Twitter – e.g. to reset the password.

See also https://docs.clearurls.xyz/1.22.0/further_readings/excluded_fields/ and https://gitlab.com/ClearURLs/rules/-/merge_requests/21 for more information.

**Comment by KevinRoebert** [comment]
> [CUserver.zip](https://github.com/ClearURLs/Rules/files/8149140/CUserver.zip)

I've found the error. Your `data.minify.json` has a new-line at the end of the file. Thus, the SHA256 hash does not match. If you remove the new-line at the end of the file, everything will work.
