### ISSUE TITLE
False positive: Sendle shipment tracking URLs

### ISSUE THREAD

**Issue by kleinfreund** [ClearURLs/Rules#46]
Sendle shipment tracking URLs are stripped inappropriately.

* Before processing URL: `https://track.sendle.com/tracking?ref={referenceNumber}`
* After processing URL: `https://track.sendle.com/tracking
* Rule: `(?:%3F)?ref_?`

This results in Sendle showing the following error:

> Looks like that number isn’t quite right. Check the reference number you were given and try again.

**Comment by maxxyme** [comment]
Hello, I've got the same problem with the French shipping service "Relais Colis".

ex. URL https://service.relaiscolis.com/wssuivicoliscritere/PageSuivi.aspx?Ref=VD238002675401
is processed to https://service.relaiscolis.com/wssuivicoliscritere/PageSuivi.aspx thus page says "La référence du colis n'est pas fournie" and I can't follow my packet.

**Comment by maxxyme** [comment]
why... "as [not planned]"?
