### ISSUE TITLE
Breaks Swedish eID setup

### ISSUE THREAD

**Issue by melissis** [ClearURLs/Rules#77]
These need exceptions:
`https://cu.bankid.com/cu/enroll-start?ref=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
`https://cu.bankid.com/mobile-enrollment-current/?ref=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
`https://cu.bankid.com/cu/list-start?ref=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
`https://cu.bankid.com/list-and-revoke-v1/?ref=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

This is legitimate and required tracking.
You cannot get the [BankID](https://en.wikipedia.org/wiki/BankID) eID from bankid.com directly, you have to log in to your online bank (e.g. Handelsbanken, SEB, Swedbank), and there you choose to setup an eID, and then they open a new window or tab that goes to cu.bankid.com (with the tracking parameter) and you complete the setup there.

**Comment by iam-py-test** [comment]
Caused by https://github.com/ClearURLs/Rules/blob/fddc7e69cab559c71b68d793c814b016e7247344/data.min.json#L266
