### ISSUE TITLE
Facebook `mibextid`

### ISSUE THREAD

**Issue by kowith337** [ClearURLs/Rules#83]
I'm often see this parameter from most sites that share `Facebook` post link externally, e.g. Nitter (Privacy-friendly frontend of `Twitter`), certain news hub site, etc.

From my history, this parameter doesn't appears from my eyes before and while using `Facebook` long time ago, or they have used another parameter before changed to this (e.g. `sfnsn`), because of that, assuming this parameter is useless and can be open without it.

Example link: `https://mbasic.facebook.com/story.php?story_fbid=pfbid0TiRyHT5qxsECdJiAcfMxF5DqFDp4TzS3KLd5PEvmCHqHkU9obq3vdBKd64Tm6yuAl&id=100044610421582&mibextid=Nif5oz`

**Comment by KevinRoebert** [comment]
Fixed by https://github.com/ClearURLs/Rules/pull/103
