### ISSUE TITLE
[Candidate] YouTube `si`

### ISSUE THREAD

**Issue by kowith337** [ClearURLs/Rules#87]
Example: `https://youtube.com/watch?v=7s6tufofYrg&si=CBdq-ZOZZRzc2qpu`

Just see some peoples share certain `YouTube` links that not `youtu.be` but directly `youtube.com/watch`, however, I've also see `si` parameter behind and not yet know that what it used for.
Note that it seems fine to open only `v` parameter if users intent to share full URL regardless of having `si` parameter or not.

**Comment by Neustradamus** [comment]
@kowith337: Thanks for your ticket, I think that you can do here too:
- https://gitlab.com/ClearURLs/rules/-/issues

**Comment by Gymcap** [comment]
I made a pull request to fix this a few days ago: https://github.com/ClearURLs/Rules/pull/92
